// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const getAllFeedsWithUsernames = `-- name: GetAllFeedsWithUsernames :many
SELECT 
    feeds.name AS feed_name,
    feeds.url AS feed_url,
    users.name AS username
FROM feeds
JOIN users ON feeds.user_id = users.id
`

type GetAllFeedsWithUsernamesRow struct {
	FeedName string
	FeedUrl  string
	Username string
}

func (q *Queries) GetAllFeedsWithUsernames(ctx context.Context) ([]GetAllFeedsWithUsernamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedsWithUsernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedsWithUsernamesRow
	for rows.Next() {
		var i GetAllFeedsWithUsernamesRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
